const products = [
    {
        "id": 0,
        "category_id": 0,
        "reference": "Call of Duty®: Black Ops 4",
        "producer": "Activision",
        "year_release": 2018,
        "price": 44.85,
        "thumbnail": "https://images.greenmangaming.com/d50607100e514337bba9427d64a394af/6dbc86cf4728496a908163171a703398.jpg",
        "image": "https://s3.dexerto.com/thumbnails/_thumbnailLarge/when-does-black-ops-4-and-blackout-release.jpg",
        "description": "Call of Duty®: Black Ops 4 features gritty, grounded, fluid Multiplayer combat, the biggest Zombies offering ever with three full undead adventures at launch, and Blackout, where the universe of Black Ops comes to life in one massive battle royale experience. Black Ops 4 will be the most robust, refined, and customizable Call of Duty® PC shooter experience ever created with uncapped framerate, 4K resolution, HDR, support for ultrawide monitors and additional features built for the PC community.",
        "stock": 33
      },
      {
        "id": 1,
        "category_id": 0,
        "reference": "Assassin's Creed Odyssey",
        "producer": "Ubisoft",
        "year_release": 2018,
        "price": 40.19,
        "thumbnail": "https://images.greenmangaming.com/15654d52033c4cd2bcf649f14956846d/cc7bfa28594b4c51a4711ffcd778a32b.jpg",
        "image": "http://www.powerpyx.com/wp-content/uploads/assassins-creed-odyssey-wallpaper.jpg",
        "description": "Choose your fate in Assassin's Creed® Odyssey. From outcast to living legend, embark on an odyssey to uncover the secrets of your past and change the fate of Ancient Greece.",
        "stock": 11
      },
      {
        "id": 2,
        "category_id": 0,
        "reference": "Fallout 76",
        "producer": "Bethesda",
        "year_release": 2018,
        "price": 46.89,
        "thumbnail": "https://images.greenmangaming.com/f54d7caca8b84498bcd933db2bd25cdc/62b91b937d034e4aa0ecd414d6d0353e.jpg",
        "image": "https://media.comicbook.com/2018/06/fallout-76-1116648-1280x0.jpeg",
        "description": "Bethesda Game Studios, the award-winning creators of Skyrim and Fallout 4, welcome you to Fallout 76, the online prequel where every surviving human is a real person. Work together, or not, to survive. Under the threat of nuclear annihilation, you’ll experience the largest, most dynamic world ever created in the legendary Fallout universe",
        "stock": 27
      },
      {
        "id": 3,
        "category_id": 0,
        "reference": "Shadow of the Tomb Raider",
        "producer": "Square Enix",
        "year_release": 2018,
        "price": 30.00,
        "thumbnail": "https://images.greenmangaming.com/e8810e657f084e9bbb3d039fce20729e/b707d71565f1452b9f60c233d5682912.jpg",
        "image": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/clans/32341898/5b83592ca76d41f1f2264f2122a617c7663efd36.png",
        "description": "Wrapping up a trilogy that revived and revitalised Lara Croft for a new generation, Shadow of the Tomb Raider maintains a base level of excellence in action, puzzling and platforming - but it also isn't afraid to take a few risks.",
        "stock": 0
      },
      {
        "id": 4,
        "category_id": 0,
        "reference": "ARK: Survival Evolved",
        "producer": "Studio Wildcard",
        "year_release": 2017,
        "price": 16.50,
        "thumbnail": "https://images.greenmangaming.com/810ef297b8c7491ab351013435d03862/a328ced9a6164c58ad9b41908827e432.jpg",
        "image": "https://i.ytimg.com/vi/5fIAPcVdZO8/maxresdefault.jpg",
        "description": "As a man or woman stranded naked, freezing and starving on the shores of a mysterious island called ARK, you must hunt, harvest resources, craft items, grow crops, research technologies, and build shelters to withstand the elements. Use your cunning and resources to kill or tame & breed the leviathan dinosaurs and other primeval creatures roaming the land, and team up with or prey on hundreds of other players to survive, dominate... and escape",
        "stock": 55
      },
      {
        "id": 5,
        "category_id": 0,
        "reference": "Shadow of the Tomb Raider - Croft Edition",
        "producer": "Square Enix",
        "year_release": 2018,
        "price": 45.00,
        "thumbnail": "https://images.greenmangaming.com/13233f66337548548147d7adde68168c/5c4832f83b2f4f4390f0cfd83f8a1818.jpg",
        "image": "https://www.gamereactor.dk/media/grtv/41/374153_w926.jpg",
        "description": "Enobimru uj hap ana vebro kuthemo zu othi pan feizesew gu kebbo wi umgemga zi epeijieze. Kite ha ler ab gosnujfu denbe sed badapo unobo raalowuc aro gu. Lebas wi wumfimu ituwu pibmega wuz daiseko pe anuka jin jeovzu viislul ahemo. Vijelmid molopro ruvki zaruzo vobpicdu irbu ca gefeh vin dusoc poffufuk gewe veedfe ogiwi mawetug hol hicana. Tubufun sebi fovlo sul cud corceckuz su iduwe mampoupa mukaale huwu tejaero itanozpe hioma ishog gib omhon zumi.",
        "stock": 197
      },
      {
        "id": 6,
        "category_id": 0,
        "reference": "Middle-earth: Shadow of War Definitive Edition",
        "producer": "Warner Bros",
        "year_release": 2018,
        "price": 59.99,
        "thumbnail": "https://images.greenmangaming.com/1bd6a904fcd946928ed1f120f5047d38/343030b224b74c6fa9e83a8748b4b7a0.jpg",
        "image": "https://i.ytimg.com/vi/jh29z5EHA7M/maxresdefault.jpg",
        "description": "Row sokelikaz vedtog wo jehvobze eb vud orojakter na pouhu ze no cekacuw cutajus mu sehnukzo. Comemagu uszubdur ha helidgu diphot ka vuwi joij ma icucioku dohhub ubwi naziric ha duv uzi. Ukgahriv javdit piv nalri eh jupe ni docim fik came otupu te bojoniiw. Uhujbe agam bov hadokop be ge um so azda vausu jeh puepegij ho ji.",
        "stock": 226
      },
      {
        "id": 7,
        "category_id": 0,
        "reference": "Far Cry 5",
        "producer": "Ubisoft",
        "year_release": 2018,
        "price": 36.81,
        "thumbnail": "https://images.greenmangaming.com/896b10c3828d4e86ab96748ff58b5e9d/a26f128d23bc420c8cc2a2a676ec28ec.jpg",
        "image": "https://store.ubi.com/on/demandware.static/-/Sites-masterCatalog/default/dw7f5afc18/images/large/5a54e84aca1a64a30179854a-collectible-1.jpg",
        "description": "Gujebaz mollumse zebo lure vuvol ke lagvuf raezazoj lu zabbil zi rujjipsol ebtogasu epozom. Fiupa gag sakoke gedguczow raaho pi piz vumbafa hittem fahmiw zarecve fa dotu. Jus ke pugla cavuhzun to jurzi mubowi ri levmelumu os azu omuihoci ig.",
        "stock": 133
      },
      {
        "id": 8,
        "category_id": 0,
        "reference": "No Man's Sky",
        "producer": "Hello Games",
        "year_release": 2016,
        "price": 46.07,
        "thumbnail": "https://images.greenmangaming.com/6266c482fa294bfd8ab1526f2d1cb4eb/0a6ed31e7e4e473ba7084e0adda12285.jpg",
        "image": "https://i.ytimg.com/vi/ihzO19neuZo/maxresdefault.jpg",
        "description": "Tim pulep cu atuwa hupzokhar vekla pa fi nanuk alanet ti hamwub afrewo eviigi mum vatvuab mef fin. Fukihokom ictipfu we se pecehauv ipajifut petuc husmo gevina agelit fah jipavahu ruzah. Orasili tig ces midoroka wuz fevig vovi onetaw luriwu ik taf jis mi huzreco. Cesocazu ciz lefo ujo gomsujej de bitewgep otijil wilse ilegeefe riz bof teecte ritlecsu he kewav. Ku kimofdav tebpeh visgese pumpod kod zizop ewomavam te rut gulipda nizahgus wisfo ucu hone wirbob lojcajka. Si ceevi li febihzid hod iku nobgo kic iv japu una li ipo umfofale mowdunsi tun how pek. Ahbokva me obago ilatirip pi ha nibonbez kah wof gibuv fupa kem.",
        "stock": 10
      },
      {
        "id": 9,
        "category_id": 0,
        "reference": "Monster Hunter World (PC)",
        "producer": "Capcom",
        "year_release": 2018,
        "price": 46.07,
        "thumbnail": "https://images.greenmangaming.com/21ce1dc4b08045df97533e1caaf955c9/952ef32554c54629a9724bb371a5bfdd.jpg",
        "image": "https://compass-ssl.microsoft.com/assets/7d/df/7ddf36fd-d09b-467d-aac6-1f5b491d3b7f.jpg?n=Monster-Hunter-World_GLP-Page-Hero-1084_1920x600.jpg",
        "description": "Uwun wuci namiwoc roniz je ino agacuczij waz seowi aspifze jer zokisror wosocwa digge he. Rama enigumo ow pikobpe enikud gebset ojoemefij ki ihe powa wabriv ewi. Pamsawre sihjo pibcit ho es namuw bi ko ci revitrem nuf nogseslu johzuc.",
        "stock": 23
      },
      {
        "id": 10,
        "category_id": 1,
        "reference": "DRAGON QUEST® XI: Echoes of an Elusive Age™ - Digital Edition of Light",
        "producer": "Square Enix",
        "year_release": 2018,
        "price": 41.99,
        "thumbnail": "https://images.greenmangaming.com/e7de096e7a3543178d5e301abcac4c65/427e01bd94144a0fad2a92c0b9074b3c.jpg",
        "image": "https://images.greenmangaming.com/e7de096e7a3543178d5e301abcac4c65/427e01bd94144a0fad2a92c0b9074b3c.jpg",
        "description": "Vuvberpij ozoon hordail no dihfigo wucedit woko zah bun nosudedab gon havipju butebar abiuhito teevsug. Vef di or si gesiw mo boh tegosneb tubew amiewmez ivi nacan. Uliiro jipafu bemozjat ma jinbe boz vafgem guv cisvuseh aj icu ju nofuw ra zesumit iwkil pewto pe. Guldid bok lutivu recseuj gajma mu azi bak maljofoge dimdegvuz san majdus ro jalej. Pad age akfe atujvuh uru ek ta fekucji jacizsi apvuv he neodjif iguag li.",
        "stock": 0
      },
      {
        "id": 11,
        "category_id": 1,
        "reference": "NieR: Automata",
        "producer": "Square Enix",
        "year_release": 2017,
        "price": 50.1,
        "thumbnail": "https://images.greenmangaming.com/86db9f9d18b4437ba96735182053e638/8c73caa5666143d68c37cbab6bf89472.jpg",
        "image": "https://cdn3.dualshockers.com/wp-content/uploads/2018/06/NieRAutomata.jpg",
        "description": "Len haw tok pirliz jasedeece jar dajra tal imhed zi ipadowe elutodu simde gig is. Rasfo vafar ov kupdad gozso focbot le fac ruifefo uluvew fot apo difebcur. Lucu de sezudro izu saf bel bub ri hap dunu ihucamud javonsez. Guz koja mohlahhaj semenhi fogog ej pakselab meziz elzenzes jeuhla vud uhe cezudmad moveuw as vej ufeovrih jes. Sipbu uncuse riggivih vackohep ha nu vag catse edouwi no kazo to duwriv damora omticej. Mo hivun desiadi okbon elizow kifob gavzaj biomenot gakivo hitazzin mik tid sumotev piurcal at libga bal. Guh efiubzih idaipro ramipi gom tuhwu ver worci awkiguj zukiza fi ca fos mawmew soweccow ahno.",
        "stock": 68
      },
      {
        "id": 12,
        "category_id": 1,
        "reference": "PREY - Mooncrash",
        "producer": "Bethesda",
        "year_release": 2018,
        "price": 10.00,
        "thumbnail": "https://images.greenmangaming.com/9464f77d2b2e442596736be48253f138/a652404368e345759f2f503ee69a815b.jpg",
        "image": "https://i.ytimg.com/vi/ySVBHI2OeAg/maxresdefault.jpg",
        "description": "Dew gojrurdab gufroule il juz pacobno taon ca owoema owiice hecak ga hesorun cepnevta. Ovawenir enewod beloudo run aloda gep ni idaratsaz vaku fafam agamieso cezwalwop koh te ge. Cipe usovetij ovcosad sa utaco bapli nibo apize re kanopbig jocodjo unozero agnu ohe elta. Mavizer oskurge vad roklape cenugato vi di no ev giriwoc vo kikaaga sul isi.",
        "stock": 2
      },
      {
        "id": 13,
        "category_id": 1,
        "reference": "Sid Meier’s Civilization® VI: Rise and Fall",
        "producer": "2K Games",
        "year_release": 2018,
        "price": 26.86,
        "thumbnail": "https://images.greenmangaming.com/466958d307bd4cf686f788fc161c9bf5/ea1e04b8ec674ba3a51ffbd11861d5e2.jpg",
        "image": "https://static.gamespot.com/uploads/screen_kubrick/1197/11970954/3333471-trailer_civvi_cree_20180102.jpg",
        "description": "Bad vogeab tadassos mehamfe tuhkevzo bepalzan ahatmo lev kunjut fuuhe likdubnol poazli kavduvu iwoza cid zirjefal pipo. Zajubadi zehampo su eruzede zam gohise buzigof demejfuz wumjavuf moliv ivlo cocnojoho owsohnar nuowfuf miges. Woflador upanocko acakew juzerofav sap ta zimejuke ehjasike wogfag omukisug tacanu pabsoto.",
        "stock": 45
      },
      {
        "id": 14,
        "category_id": 1,
        "reference": "Farming Simulator 19",
        "producer": "Focus Home Interactive",
        "year_release": 2018,
        "price": 54.46,
        "thumbnail": "https://images.greenmangaming.com/d5059951356144f4977098bfacc76095/8446d67414234c6abe9e29a8a38a6ece.jpg",
        "image": "https://i.ytimg.com/vi/XOLBaaf2fGw/maxresdefault.jpg",
        "description": "Zud fulavhat hobleso kuefegog jahiz ehneki newperzal endoawe wudan lafmais kaeji ohe wupsub tu jaew runoso lewadhu. Duruzuf sukug udi sownapaf ekuli ihora beljened ruhujoji godputden mi ur tiigivol ekefagod ficame diaso cuhesha. Ijtar cuazfo red teoc cagkokci ib dekeclu cigo deliclim duhac elo owfa patoic tof mefed mokzu deseg okwozjes.",
        "stock": 141
      },
      {
        "id": 15,
        "category_id": 1,
        "reference": "Sunset Overdrive",
        "producer": "THQ Nordic",
        "year_release": 2018,
        "price": 52.08,
        "thumbnail": "https://images.greenmangaming.com/ecef5c39e1b643f38abae8e06d1365c0/1429f8728236489f88825abc212ee4ae.jpg",
        "image": "https://i.ytimg.com/vi/Cp5krGk23zk/maxresdefault.jpg",
        "description": "Ni opojol su ihu sej koczuazu fon ve bet fiwwevu gopheer fojneb. Emohejnim bepowe ze vurta us bi jo tovof gikoneuk megacrit hidpo aba hunkejiv gifeuzu. Pehnif fuz usa timem suvratmi edade fi tobuc de ja pumwihtof jorhut ikeesope umdecte fepdetat aseweuzu. Baclujro mimpavel zashiete inagifkuk beh ferfan ta bohilelu hoh pecaape joatano hocewroj de lejma. Diulovif bavuho rekhabo ga ecoval rewi iz dige mak san umkaj henhoate nigsanos ta.",
        "stock": 115
      },
      {
        "id": 16,
        "category_id": 1,
        "reference": "Frostpunk",
        "producer": "11 Bit Studios",
        "year_release": 2018,
        "price": 37.94,
        "thumbnail": "https://images.greenmangaming.com/849120b396384e6f8e6701c91bcbfe4c/acca220fb8fd4229a32e7c1f7744ecfa.jpg",
        "image": "https://i.ytimg.com/vi/DMmJay3ah2I/maxresdefault.jpg",
        "description": "Hacsil idi aco hev kav zejipsef fik vi aj poljinvuz omtobuc wadomas naonusak. Bihkase jiljocas cisjuk lolsumnoh iffif fatekgo emzamoce wivi taot ha zarwe upoci lawur. Ujfuoju ag edo vabih az zi ejuiw zaemsa safuha jug po ufpaw uze ucbiuva. On mu mezfop me deumkip malofu hup apa vemuj waz arruv aflodilu su fonsep go hetavo fohiwma olivesel. Nesek nen pigo fafit ihued bav kivdes lolup tebfewse wabdefcab fekim li ci kadunaz re.",
        "stock": 216
      },
      {
        "id": 17,
        "category_id": 1,
        "reference": "Injustice™ 2 Legendary Edition",
        "producer": "Warner Bros",
        "year_release": 2018,
        "price": 64.53,
        "thumbnail": "https://images.greenmangaming.com/156837895ae648309613fb192edcbc50/7cbb061d314743ca8e71e42973816692.jpg",
        "image": "https://media.comicbook.com/2018/03/injustice2wa-1096653-1280x0.jpeg",
        "description": "Lowunde niwuwduj hu ga femkeshuc mo jo edoohsi welogri ma omuro jeg. Fe ot kiveko cuvoh cawtik larawiv cazu vutvozil dep ja aje cavuz docdogar sarva upura puzpair. Zilmoc lumi kifwovwiv elinula cabikrof ru punra muuto zi zaola zan jober dudek paofe ki oskepzar bo. Gu jep kuv ju abi vezac sojdiare kesbik soiwopuh nerzauk wuwten tigek bibveidi lucani mahir je.",
        "stock": 0
      },
      {
        "id": 18,
        "category_id": 1,
        "reference": "Wolfenstein II: The New Colossus Digital Deluxe Edition",
        "producer": "Bethesda",
        "year_release": 2017,
        "price": 19.43,
        "thumbnail": "https://images.greenmangaming.com/2ac02b0ca0f44cb197f843032d905a8d/3f49fc79184c407690765e7cfae974d1.jpg",
        "image": "https://static.gamespot.com/uploads/scale_medium/1197/11970954/3246555-wolfensteinii.jpg",
        "description": "Dubal depe jumti laz kafza gael dupjiiva suwdodgo ujzon itela giom liletiha. Fi okaranada pofcehe leldabu gec zadroj zaup zapdo fup wu nijsov pi ni fifo sijhez. Apkaghu popfik kefsarlo aj juz wom edvif vohdumwi liwif obeceku jic vuhiji soz bo ditka hustiwe wo. Somim tuwe ref nas pab di tewgef rohumavu nogwav fiogcud imebe lewo acumsa ara ih puvtap nohfifsec. Lahnawbij basisev nujaba hubka etozil fokoaso hoafnuh hobo bo fe mide pamwenoj hajekaz. Kabukon kicselho lavak jovivubo og oz hu mosgi ef ladsi orliz ehanegmoh.",
        "stock": 184
      },
      {
        "id": 19,
        "category_id": 1,
        "reference": "Pillars of Eternity II: Deadfire Obsidian Edition",
        "producer": "Versus Evil LLC",
        "year_release": 2018,
        "price": 44.99,
        "thumbnail": "https://images.greenmangaming.com/153b77af264541a4aac6f2720dca90b2/a2e4d56ce7464864bfe3ae24b9f41fb4.jpg",
        "image": "https://images-2.gog.com/2e6a071865dabab3bb409e3c72bd4eee0a0d7255e721037c2ebb0e97d5f93ecc.jpg",
        "description": "Vatgudtu it kat jar bezbo wulbiro pujisit di bu ozo ivepu elkan tosut. Hew sudrap wus efdobvi ucgebca hi vanza joje woffiki mosu jufecu gemvusid is zo jaffagdu pitonfu. Ol ine nub col sanovfa poj wef zujvitu leg dezposze vefrejuc dajibu makecuad awu faoju accalzak ta. Biami zihba lefo suromral wuzkalcab pako ra germahij re cofjugceg vu befcuh siberweb woco voz juw ah. Gi poplezlum muzi cab fad fok hon va ire puctip vorubje rar mer uto. Makcavu raggi ikoguj bodsi his tohkiudo morsajan aherapi guvfum zuboheko hud ti pije pogvamof punaiti mi epoofe.",
        "stock": 189
      }
  ]

  export default products;